import Link from 'next/link'
import Image from 'next/image'
import { ArrowLeft } from 'lucide-react'
import { Logo } from '@/components/logo'

export const metadata = {
  title: 'Privacy Policy | JARVIS-X Security',
  description: 'Privacy Policy for JARVIS-X Security — AI-powered email threat detection platform.',
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-950 text-gray-900 dark:text-gray-100">
      {/* Header */}
      <header className="border-b border-gray-200 dark:border-gray-800 sticky top-0 bg-white/80 dark:bg-gray-950/80 backdrop-blur-sm z-10">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Logo href="/" size="md" />
          <Link
            href="/"
            className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Home
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        {/* Title */}
        <div className="mb-10">
          <h1 className="text-4xl font-bold tracking-tight mb-3">Privacy Policy</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">Last Updated: April 2026</p>
          <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
            Effective for all users of{' '}
            <span className="text-blue-600 dark:text-blue-400">jarvisxsecurity.com</span>
          </p>
        </div>

        <div className="space-y-10 text-[15px] leading-7 text-gray-700 dark:text-gray-300">

          {/* 1. Introduction */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3">
              1. Introduction
            </h2>
            <p>
              JARVIS-X Security (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;) operates the AI-powered email security
              platform available at <span className="text-blue-600 dark:text-blue-400">jarvisxsecurity.com</span>.
              This Privacy Policy explains how we collect, use, store, and protect your information when
              you use our service. By using JARVIS-X, you agree to the terms described in this policy.
            </p>
            <p className="mt-3">
              We are committed to handling your data with transparency and care. Our sole purpose is to
              protect your email security — we do not sell, share, or monetize your personal data.
            </p>
          </section>

          <hr className="border-gray-200 dark:border-gray-800" />

          {/* 2. Information We Collect */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3">
              2. Information We Collect
            </h2>
            <p className="mb-3">We collect only what is necessary to provide the service:</p>
            <ul className="space-y-2 list-none">
              {[
                {
                  label: 'Gmail OAuth Access',
                  detail:
                    'When you connect your Gmail account, we request read-only access to scan incoming emails for threats. We use OAuth 2.0 — we never store your Google password.',
                },
                {
                  label: 'Email Metadata',
                  detail:
                    'Sender address, subject line, received timestamp, and email body text are processed for threat analysis. Attachments are not stored.',
                },
                {
                  label: 'Account Information',
                  detail:
                    'Your email address, phone number (for alerts), and account preferences.',
                },
                {
                  label: 'Threat Analysis Results',
                  detail:
                    'Risk scores, threat classifications, and detection reasons generated by our AI engine.',
                },
                {
                  label: 'Usage Data',
                  detail:
                    'Basic usage logs such as login timestamps and feature interactions for service improvement.',
                },
              ].map(({ label, detail }) => (
                <li key={label} className="flex gap-3">
                  <span className="mt-1 h-2 w-2 rounded-full bg-blue-500 flex-shrink-0" />
                  <span>
                    <strong className="text-gray-900 dark:text-gray-100">{label}:</strong>{' '}
                    {detail}
                  </span>
                </li>
              ))}
            </ul>
          </section>

          <hr className="border-gray-200 dark:border-gray-800" />

          {/* 3. How We Use Your Information */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3">
              3. How We Use Your Information
            </h2>
            <p className="mb-3">Your data is used exclusively for the following purposes:</p>
            <ul className="space-y-2 list-none">
              {[
                'Scanning incoming emails for phishing, malware, and social engineering threats',
                'Generating risk scores and threat classifications using our AI engine',
                'Sending security alerts via WhatsApp and voice calls when threats are detected',
                'Maintaining your account and dashboard history',
                'Improving detection accuracy through aggregated, anonymized pattern analysis',
                'Responding to your support requests',
              ].map((item) => (
                <li key={item} className="flex gap-3">
                  <span className="mt-1 h-2 w-2 rounded-full bg-blue-500 flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mt-4 p-4 bg-blue-50 dark:bg-blue-950/40 rounded-lg border border-blue-200 dark:border-blue-800 text-blue-800 dark:text-blue-200 text-sm">
              We do <strong>not</strong> read, store, or share the full content of your emails beyond
              what is necessary for threat detection. We do not use your emails for advertising or
              train general-purpose AI models on your personal email data.
            </p>
          </section>

          <hr className="border-gray-200 dark:border-gray-800" />

          {/* 4. Data Storage */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3">
              4. Data Storage
            </h2>
            <p className="mb-3">
              Your data is stored securely using industry-standard infrastructure:
            </p>
            <ul className="space-y-2 list-none">
              {[
                {
                  label: 'Database',
                  detail:
                    'All account data, email records, and threat history are stored in Supabase (PostgreSQL), hosted on secure cloud infrastructure with row-level security (RLS) enabled.',
                },
                {
                  label: 'Gmail Tokens',
                  detail:
                    'OAuth access tokens are encrypted at rest using AES-256-CBC encryption before being stored in our database. Your Google credentials are never stored in plain text.',
                },
                {
                  label: 'Retention',
                  detail:
                    'Email scan records are retained for as long as your account is active. You may request deletion at any time.',
                },
                {
                  label: 'Backups',
                  detail:
                    'Database backups are encrypted and stored securely. Backups are retained for a limited period for disaster recovery purposes.',
                },
              ].map(({ label, detail }) => (
                <li key={label} className="flex gap-3">
                  <span className="mt-1 h-2 w-2 rounded-full bg-blue-500 flex-shrink-0" />
                  <span>
                    <strong className="text-gray-900 dark:text-gray-100">{label}:</strong>{' '}
                    {detail}
                  </span>
                </li>
              ))}
            </ul>
          </section>

          <hr className="border-gray-200 dark:border-gray-800" />

          {/* 5. Third Party Services */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3">
              5. Third-Party Services
            </h2>
            <p className="mb-4">
              JARVIS-X integrates with the following third-party services to deliver its features.
              Each service has its own privacy policy.
            </p>
            <div className="space-y-4">
              {[
                {
                  name: 'Google (Gmail API)',
                  usage:
                    'Used to access your inbox for email scanning. Access is granted via OAuth 2.0 and can be revoked at any time from your Google Account settings.',
                  link: 'https://policies.google.com/privacy',
                },
                {
                  name: 'Meta (WhatsApp Business Cloud API)',
                  usage:
                    'Used to deliver security alert notifications to your WhatsApp number when a threat is detected.',
                  link: 'https://www.whatsapp.com/legal/privacy-policy',
                },
                {
                  name: 'Twilio',
                  usage:
                    'Used to make automated voice call alerts to your phone number for high-severity threats.',
                  link: 'https://www.twilio.com/en-us/legal/privacy',
                },
                {
                  name: 'Supabase',
                  usage:
                    'Our database and authentication infrastructure provider. All data stored through JARVIS-X resides in Supabase-managed PostgreSQL.',
                  link: 'https://supabase.com/privacy',
                },
                {
                  name: 'Stripe',
                  usage:
                    'Used for processing subscription payments. We do not store your payment card details — all billing is handled directly by Stripe.',
                  link: 'https://stripe.com/privacy',
                },
              ].map(({ name, usage, link }) => (
                <div
                  key={name}
                  className="p-4 rounded-lg border border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-900"
                >
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <p className="font-semibold text-gray-900 dark:text-gray-100 mb-1">{name}</p>
                      <p className="text-sm">{usage}</p>
                    </div>
                  </div>
                  <a
                    href={link}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-block mt-2 text-xs text-blue-600 dark:text-blue-400 hover:underline"
                  >
                    View Privacy Policy →
                  </a>
                </div>
              ))}
            </div>
          </section>

          <hr className="border-gray-200 dark:border-gray-800" />

          {/* 6. Data Security */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3">
              6. Data Security
            </h2>
            <p className="mb-3">
              We implement multiple layers of security to protect your data:
            </p>
            <ul className="space-y-2 list-none">
              {[
                'AES-256-CBC encryption for all stored OAuth tokens',
                'JWT-based authentication with minimum 32-character secret keys',
                'HTTPS enforced on all API endpoints',
                'Row-level security (RLS) in Supabase — users can only access their own data',
                'Rate limiting on all authentication and API endpoints',
                'CORS restrictions to approved origins only',
                'Security headers enforced via Helmet.js',
              ].map((item) => (
                <li key={item} className="flex gap-3">
                  <span className="mt-1 h-2 w-2 rounded-full bg-green-500 flex-shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mt-4 text-sm text-gray-500 dark:text-gray-400">
              While we employ industry-standard security measures, no system is 100% secure. We
              encourage you to use a strong, unique password and enable two-factor authentication on
              your Google account.
            </p>
          </section>

          <hr className="border-gray-200 dark:border-gray-800" />

          {/* 7. Your Rights */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3">
              7. Your Rights
            </h2>
            <p className="mb-3">You have full control over your data:</p>
            <ul className="space-y-2 list-none">
              {[
                {
                  label: 'Access',
                  detail: 'Request a copy of all data we hold about you.',
                },
                {
                  label: 'Deletion',
                  detail:
                    'Request deletion of your account and all associated data. We will permanently delete your records within 30 days.',
                },
                {
                  label: 'Revoke Gmail Access',
                  detail:
                    'You can disconnect your Gmail account from JARVIS-X at any time via your dashboard, or directly from Google Account → Security → Third-party apps.',
                },
                {
                  label: 'Opt Out of Alerts',
                  detail:
                    'You can disable WhatsApp or voice call alerts from your account settings at any time.',
                },
                {
                  label: 'Data Portability',
                  detail: 'Request an export of your email scan history and threat reports.',
                },
              ].map(({ label, detail }) => (
                <li key={label} className="flex gap-3">
                  <span className="mt-1 h-2 w-2 rounded-full bg-blue-500 flex-shrink-0" />
                  <span>
                    <strong className="text-gray-900 dark:text-gray-100">{label}:</strong>{' '}
                    {detail}
                  </span>
                </li>
              ))}
            </ul>
            <p className="mt-4">
              To exercise any of these rights, contact us at{' '}
              <a
                href="mailto:contact@jarvisxsecurity.com"
                className="text-blue-600 dark:text-blue-400 hover:underline"
              >
                contact@jarvisxsecurity.com
              </a>
              .
            </p>
          </section>

          <hr className="border-gray-200 dark:border-gray-800" />

          {/* 8. Contact Us */}
          <section>
            <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3">
              8. Contact Us
            </h2>
            <p className="mb-4">
              If you have any questions, concerns, or requests regarding this Privacy Policy or how
              we handle your data, please reach out:
            </p>
            <div className="p-5 rounded-lg border border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-900 space-y-2 text-sm">
              <p>
                <span className="font-semibold text-gray-900 dark:text-gray-100">Company:</span>{' '}
                JARVIS-X Security
              </p>
              <p>
                <span className="font-semibold text-gray-900 dark:text-gray-100">Website:</span>{' '}
                <span className="text-blue-600 dark:text-blue-400">jarvisxsecurity.com</span>
              </p>
              <p>
                <span className="font-semibold text-gray-900 dark:text-gray-100">Email:</span>{' '}
                <a
                  href="mailto:contact@jarvisxsecurity.com"
                  className="text-blue-600 dark:text-blue-400 hover:underline"
                >
                  contact@jarvisxsecurity.com
                </a>
              </p>
            </div>
            <p className="mt-4 text-sm text-gray-500 dark:text-gray-400">
              We aim to respond to all privacy-related inquiries within 5 business days.
            </p>
          </section>

          <hr className="border-gray-200 dark:border-gray-800" />

          {/* Footer note */}
          <section className="text-sm text-gray-500 dark:text-gray-400">
            <p>
              We may update this Privacy Policy from time to time. When we make significant changes,
              we will notify you via email or a prominent notice on our platform. Your continued use
              of JARVIS-X after changes are posted constitutes your acceptance of the updated policy.
            </p>
            <p className="mt-2">
              <strong className="text-gray-700 dark:text-gray-300">Last Updated:</strong> April 2026
            </p>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-200 dark:border-gray-800 mt-16">
        <div className="max-w-4xl mx-auto px-6 py-6 flex items-center justify-between text-sm text-gray-500 dark:text-gray-400">
          <div className="flex items-center gap-3">
            <Logo href="/" size="sm" subtitle="" />
            <span>© 2026 JARVIS-X Security</span>
          </div>
          <Link href="/" className="hover:text-gray-900 dark:hover:text-gray-100 transition-colors">
            Back to Home
          </Link>
        </div>
      </footer>
    </div>
  )
}
